name: simple_schema
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/simple_schema
description: >
  Provide declarative api for creating json schema
dependencies:
  id: ">=0.0.3"

  json_schema: ">=0.0.2"

  ebisu:
      git: 
        url: git://github.com/patefacio/ebisu
        ref: HEAD

  ebisu_dlang:
      git: 
        url: git://github.com/patefacio/ebisu_dlang
        ref: HEAD

  quiver: "any"

  logging: ">=0.7.1"

# custom <simple_schema dependencies>

#  plus:
#    path: /Users/dbdavidson/dev/plusauri/dart/plus/

# end <simple_schema dependencies>

dev_dependencies:
  hop: ">=0.24.4"

# custom <simple_schema dev dependencies>
# end <simple_schema dev dependencies>


