name: simple_schema
version: 0.0.2
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/simple_schema
description: >
  Provide declarative api for creating json schema
dependencies:
  quiver: "any"
  logging: "any"

# custom <simple_schema dependencies>

  id:
    git: git://github.com/patefacio/id

  ebisu:
    git: git://github.com/patefacio/ebisu

  json_schema:
    git: git://github.com/patefacio/json_schema


# end <simple_schema dependencies>

dev_dependencies:
  unittest: ">=0.9.0 < 0.10.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <simple_schema dev dependencies>
# end <simple_schema dev dependencies>

transformers:

# custom <simple_schema transformers>
# end <simple_schema transformers>

