name: simple_schema
version: 0.0.2
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/simple_schema
description: >
  Provide declarative api for creating json schema
dependencies:
  quiver: "any"

# custom <simple_schema dependencies>

  id: "^1.0.13"

  ebisu: "^0.6.19"

  json_schema: "^1.0.3"


# end <simple_schema dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <simple_schema dev dependencies>

  test: ">=0.12.0 < 0.14.0"

# end <simple_schema dev dependencies>

dependency_overrides:
# custom <simple_schema dependency overrides>
# end <simple_schema dependency overrides>

transformers:

# custom <simple_schema transformers>
# end <simple_schema transformers>

