name: simple_schema
version: 0.0.2
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/simple_schema
description: >
  Provide declarative api for creating json schema
dependencies:
  id: ">=0.0.5"

  json_schema: ">=1.0.0"

  ebisu: ">=0.0.4"

  ebisu_dlang: ">=0.0.4"

  quiver: "any"

  logging: ">=0.7.1"

# custom <simple_schema dependencies>

# end <simple_schema dependencies>

dev_dependencies:
  hop: ">=0.27.0"

# custom <simple_schema dev dependencies>
# end <simple_schema dev dependencies>


